<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>d16a1c5a-a24b-4cdc-a070-3a8d0dda3bf7</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="IronPdf" Version="2026.4.1" />
    <PackageReference Include="MailKit" Version="4.15.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="10.0.5" />
    <PackageReference Include="MimeKit" Version="4.15.1" />
    <PackageReference Include="QRCoder" Version="1.7.0" />
  </ItemGroup>

</Project>
